### ISSUE TITLE
"The property 'DeviceId' cannot be found on this object."

### ISSUE THREAD

**Issue by NostraDavid** [markekraus/PSRAW#49]
What I try to do:

1. Log in via PSRAW
2. Remove all my comments where karma is below 10

What I got running so far:

```
$ClientID = "[MY CLIENT ID THAT STARTS WITH a7RAI3]"
$ClientSecret = ConvertTo-SecureString -String [HERE IS AN ENCRYPTED STRING]
$RedirectUri = "https://localhost:8080"
$User = "NostraDavid"
$Password = ConvertTo-SecureString -String [HERE IS AN ENCRYPTED STRING]
$Threshold = 10
$UserAgent = 'windows:markekraus-PSRAW:v0.0.0.1 (by /u/markekraus)'

$UserCredential = Get-Credential (New-Object PSCredential($User, $Password))
$ClientCredential = Get-Credential (New-Object PSCredential($ClientID, $ClientSecret))

$Params = @{
    Script           = $True
    Description      = "this is my 1337 hax for PSRAW"
    RedirectUri      = "https://localhost:8080/"
    UserAgent        = "PowerShell:PSRAW:2.0 (by /u/markekraus)"
    GUID             = "e0b05578-2629-4c2e-be8a-5168f4f84457"
    ClientCredential = $ClientCredential
    UserCredential   = $UserCredential
}
$RedditApp = New-RedditApplication @Params

$AppExportPath = '.\Remove-LowKarmaComments.xml'
$RedditApp | Export-RedditApplication -Path $AppExportPath
echo $RedditApp

$TokenExportPath = '.\Token.xml'
$RedditApp | Add-Member -NotePropertyName DeviceId -NotePropertyValue ([guid]::NewGuid()).ToString()
$RedditApp | Request-RedditOAuthToken -Script
```

When running the last line I get the following error:

```
Request-RedditOAuthToken : The property 'DeviceId' cannot be found on this object. Verify that the property exists.
At line:1 char:14
+ $RedditApp | Request-RedditOAuthToken -Script
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Request-RedditOAuthToken], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Request-RedditOAuthToken
```

Note that I literally add that property to the `$RedditApp` variable, so I'm completely lost here.

I also don't understand why `Request-RedditOAuthToken` expects the `DeviceId`, as I'm using `-Script`

**Comment by NostraDavid** [comment]
The encrypted strings were made via:

```
Write-Output (ConvertFrom-SecureString -SecureString (ConvertTo-SecureString -String "[PASSWORD]" -AsPlainText -Force))
````

Then inserting the output into the script.

**Comment by markekraus** [comment]
It probably has to do with the type on `$RedditApp` and PowerShell's messed up type scoping for PowerShell classes combined with PowerShell's wonky parameter binding from pipeline.

Instead of piping, try using the parameter:

```powershell
$token = Request-RedditOAuthToken -Script -Application $RedditApp 
```

**Comment by NostraDavid** [comment]
I'm still getting the same error.

I've debugged through your code (after I couldn't find anything in mine) and something weird is going on in `004-RedditOAuthToken.ps1`. On [**line 54**](https://github.com/markekraus/PSRAW/blob/staging/PSRAW/Classes/004-RedditOAuthToken.ps1#LC54) "`$This.DeviceId = $Content.DeviceId`", `$Content` is a parsed `$Response.Content`, but this `$Response.Content` does not contain a `DeviceId`.

Maybe Reddit changed the response data and it used to contain a DeviceId?

**Comment by markekraus** [comment]
You're not using strict mode, are you? This module is not meant for strict mode.
That's totally fine without strict mode. DeviceID just gets set to null when nothing is present.

```powershell
$a = 'test'
$b = $a.NonexistantProperty
```

It only matters when it is present on auth flows that require a device ID.

Edit:
Ah, yes I see it now in your error: `PropertyNotFoundStrict`
You will need to use this module without strictmode.

**Comment by NostraDavid** [comment]
> You're not using strict mode, are you?

**I totally was.** The reason for this is that I'm relatively new to PowerShell and wanted to follow "best practices". That'll teach me, trying to do the good thing! 🥇

Still, thanks for helping me!
